"""
Streamlit demo — Credit Card Fraud Detection
Run: streamlit run streamlit_app.py
"""
from __future__ import annotations

import pickle
from pathlib import Path

import numpy as np
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import streamlit as st

# ── Page config ────────────────────────────────────────────────────────────────
st.set_page_config(
    page_title="Credit Card Fraud Detection",
    page_icon="🛡️",
    layout="wide",
    initial_sidebar_state="expanded",
)

BUNDLE_PATH = Path("artifacts/fraud_demo.pkl")


# ── Load bundle ────────────────────────────────────────────────────────────────
@st.cache_resource(show_spinner="Loading model …")
def load_bundle() -> dict:
    if not BUNDLE_PATH.exists():
        return {}
    with open(BUNDLE_PATH, "rb") as f:
        return pickle.load(f)


bundle = load_bundle()
model = bundle.get("model")
scaler = bundle.get("scaler")
feature_cols = bundle.get("feature_cols", [])
metrics = bundle.get("metrics", {})
curves = bundle.get("curves", {})
top_features = bundle.get("top_features", [])
stats = bundle.get("dataset_stats", {})
sample_data = bundle.get("sample_data", {})

# ── Sidebar ────────────────────────────────────────────────────────────────────
with st.sidebar:
    st.image(
        "https://img.icons8.com/color/96/bank-card-front-side.png",
        width=80,
    )
    st.title("🛡️ Fraud Detection")
    st.caption("Credit Card Fraud Detection — Logistic Regression demo")
    st.divider()

    if stats:
        st.metric("Total Transactions", f"{stats['n_total']:,}")
        st.metric("Fraudulent", f"{stats['n_fraud']} ({stats['fraud_rate']*100:.2f}%)")
        st.metric("Legitimate", f"{stats['n_legit']:,}")
    st.divider()
    if metrics:
        st.metric("ROC-AUC", f"{metrics.get('roc_auc', 0):.4f}")
        st.metric("PR-AUC ★", f"{metrics.get('pr_auc', 0):.4f}")
    st.divider()
    st.caption("Model: Logistic Regression (balanced class weights)\nData: Synthetic — generated by train_demo.py")

# ── Tabs ───────────────────────────────────────────────────────────────────────
tab1, tab2, tab3, tab4 = st.tabs([
    "📊 Overview",
    "🔍 Transaction Analyzer",
    "📈 Model Performance",
    "⚙️ Pipeline Details",
])

# ══════════════════════════════════════════════════════════════════════════════
# TAB 1 — Overview
# ══════════════════════════════════════════════════════════════════════════════
with tab1:
    st.header("Dataset Overview")
    st.markdown(
        """
        Credit card fraud detection is one of the most imbalanced classification problems
        in industry. The genuine Kaggle dataset has only **~0.17 %** fraudulent transactions
        across 284,807 records. Features **V1–V28** are PCA-transformed to protect
        cardholder privacy; **Amount** and **Time** are raw.
        """
    )

    if not stats:
        st.warning("Bundle not found. Run `python train_demo.py` first.")
        st.stop()

    c1, c2, c3, c4 = st.columns(4)
    c1.metric("Transactions", f"{stats['n_total']:,}")
    c2.metric("Fraud Cases", str(stats["n_fraud"]))
    c3.metric("Fraud Rate", f"{stats['fraud_rate']*100:.2f}%")
    c4.metric("Avg. Amount", f"${stats['amount_mean']:.2f}")

    st.divider()

    col_left, col_right = st.columns(2)

    with col_left:
        st.subheader("Class Distribution")
        fig_cls = go.Figure(go.Bar(
            x=["Legitimate (0)", "Fraudulent (1)"],
            y=[stats["n_legit"], stats["n_fraud"]],
            marker_color=["#2ecc71", "#e74c3c"],
            text=[stats["n_legit"], stats["n_fraud"]],
            textposition="outside",
        ))
        fig_cls.update_layout(
            yaxis_title="Count",
            plot_bgcolor="rgba(0,0,0,0)",
            margin=dict(t=20, b=0),
        )
        st.plotly_chart(fig_cls, use_container_width=True)
        st.caption(
            "⚠️ Severe class imbalance — fraud accounts for less than 0.3 % of transactions. "
            "Standard accuracy is misleading; PR-AUC is the key metric."
        )

    with col_right:
        st.subheader("Transaction Amount Distribution")
        if sample_data and "Amount" in sample_data:
            df_sample = pd.DataFrame(sample_data)
            fig_amt = px.histogram(
                df_sample,
                x="Amount",
                color=df_sample["Class"].map({0: "Legitimate", 1: "Fraud"}),
                nbins=60,
                barmode="overlay",
                color_discrete_map={"Legitimate": "#2ecc71", "Fraud": "#e74c3c"},
                labels={"color": "Class"},
            )
            fig_amt.update_layout(
                xaxis_title="Amount ($)",
                yaxis_title="Count",
                plot_bgcolor="rgba(0,0,0,0)",
                margin=dict(t=20, b=0),
            )
            st.plotly_chart(fig_amt, use_container_width=True)

    st.divider()
    st.subheader("Amount Statistics by Class")
    amt_df = pd.DataFrame({
        "": ["Mean Amount ($)", "Median Amount ($)", "Std Dev ($)"],
        "Legitimate": [
            f"${stats['legit_amount_mean']:.2f}",
            "—",
            "—",
        ],
        "Fraud": [
            f"${stats['fraud_amount_mean']:.2f}",
            "—",
            "—",
        ],
    })
    st.dataframe(amt_df, use_container_width=True, hide_index=True)

    if sample_data:
        st.divider()
        st.subheader("Sample Transactions (first 20)")
        df_sample2 = pd.DataFrame(sample_data).head(20)
        display_cols = ["Time", "Amount"] + [f"V{i}" for i in range(1, 6)] + ["Class"]
        display_cols = [c for c in display_cols if c in df_sample2.columns]
        st.dataframe(
            df_sample2[display_cols].style.apply(
                lambda row: ["background-color: rgba(231,76,60,0.2)" if row["Class"] == 1
                             else "" for _ in row],
                axis=1,
            ),
            use_container_width=True,
        )

# ══════════════════════════════════════════════════════════════════════════════
# TAB 2 — Transaction Analyzer
# ══════════════════════════════════════════════════════════════════════════════
with tab2:
    st.header("🔍 Transaction Analyzer")
    st.markdown(
        "Enter transaction features below to get a real-time fraud probability score."
    )

    if model is None or scaler is None:
        st.warning("Model not loaded. Run `python train_demo.py` first.")
        st.stop()

    with st.form("predict_form"):
        st.subheader("Transaction Details")

        col_a, col_b = st.columns(2)
        with col_a:
            time_val = st.number_input("Time (seconds since first tx)", min_value=0.0, value=50000.0, step=1000.0)
        with col_b:
            amount_val = st.number_input("Amount ($)", min_value=0.0, value=120.0, step=1.0)

        st.subheader("Feature Values (V1 – V28 — PCA components)")
        st.caption("For a normal/legitimate transaction, values near 0 are typical.")

        v_cols_input: list[float] = []
        col_groups = [st.columns(7) for _ in range(4)]
        for row_i, row_cols in enumerate(col_groups):
            for col_j, col in enumerate(row_cols):
                vi = row_i * 7 + col_j + 1
                if vi > 28:
                    break
                with col:
                    v_cols_input.append(
                        st.number_input(f"V{vi}", value=0.0, format="%.3f", key=f"v{vi}")
                    )

        submitted = st.form_submit_button("🔍 Analyze Transaction", type="primary", use_container_width=True)

    if submitted:
        raw_features = [time_val, amount_val] + v_cols_input[:28]
        # Re-order to match training feature columns (Time, Amount, V1-V28)
        feature_order = ["Time", "Amount"] + [f"V{i}" for i in range(1, 29)]
        feature_order = [f for f in feature_order if f in feature_cols]

        raw_arr = np.array(raw_features[:len(feature_order)]).reshape(1, -1)
        # Build with correct ordering
        input_dict = {"Time": time_val, "Amount": amount_val}
        for i, v in enumerate(v_cols_input[:28], start=1):
            input_dict[f"V{i}"] = v
        ordered = np.array([input_dict.get(f, 0.0) for f in feature_cols]).reshape(1, -1)

        scaled = scaler.transform(ordered)
        prob_fraud = float(model.predict_proba(scaled)[0, 1])
        pred_class = int(model.predict(scaled)[0])

        st.divider()
        r1, r2, r3 = st.columns(3)
        r1.metric("Fraud Probability", f"{prob_fraud*100:.1f}%")
        r2.metric("Prediction", "🚨 FRAUD" if pred_class == 1 else "✅ LEGITIMATE")
        r3.metric("Confidence", f"{max(prob_fraud, 1-prob_fraud)*100:.1f}%")

        # Gauge chart
        fig_gauge = go.Figure(go.Indicator(
            mode="gauge+number+delta",
            value=prob_fraud * 100,
            number={"suffix": "%", "font": {"size": 36}},
            title={"text": "Fraud Probability", "font": {"size": 18}},
            delta={"reference": 50, "increasing": {"color": "#e74c3c"}, "decreasing": {"color": "#2ecc71"}},
            gauge={
                "axis": {"range": [0, 100], "tickwidth": 1},
                "bar": {"color": "#e74c3c" if prob_fraud > 0.5 else "#2ecc71"},
                "steps": [
                    {"range": [0, 30], "color": "rgba(46,204,113,0.15)"},
                    {"range": [30, 70], "color": "rgba(241,196,15,0.15)"},
                    {"range": [70, 100], "color": "rgba(231,76,60,0.15)"},
                ],
                "threshold": {
                    "line": {"color": "red", "width": 4},
                    "thickness": 0.75,
                    "value": 50,
                },
            },
        ))
        fig_gauge.update_layout(height=300, margin=dict(t=30, b=0, l=40, r=40))
        st.plotly_chart(fig_gauge, use_container_width=True)

        if pred_class == 1:
            st.error(
                "⚠️ **FRAUD ALERT** — This transaction has been flagged as potentially fraudulent. "
                f"Fraud probability: **{prob_fraud*100:.1f}%**."
            )
        else:
            st.success(
                f"✅ **Transaction appears legitimate.** Fraud probability: **{prob_fraud*100:.1f}%**."
            )

    st.divider()
    st.subheader("Quick-Load Presets")
    col_p1, col_p2 = st.columns(2)
    col_p1.info("**Typical Legitimate Transaction**\nV1–V28 near 0, Amount ~$100, Time ~50,000s")
    col_p2.warning("**Suspicious Pattern**\nV-features with large magnitudes (±3+), unusual Amount")

# ══════════════════════════════════════════════════════════════════════════════
# TAB 3 — Model Performance
# ══════════════════════════════════════════════════════════════════════════════
with tab3:
    st.header("📈 Model Performance")

    if not metrics or not curves:
        st.warning("Metrics not available. Run `python train_demo.py` first.")
        st.stop()

    st.info(
        "**Why PR-AUC matters more than ROC-AUC for fraud detection:** "
        "With extreme class imbalance (~0.17% fraud), a model can achieve >99% ROC-AUC "
        "while still missing most fraudulent transactions. PR-AUC (Precision-Recall Area "
        "Under Curve) directly measures performance on the minority class."
    )

    m1, m2, m3, m4 = st.columns(4)
    report = metrics.get("classification_report", {})
    fraud_report = report.get("1", {})
    m1.metric("ROC-AUC", f"{metrics.get('roc_auc', 0):.4f}")
    m2.metric("PR-AUC ★", f"{metrics.get('pr_auc', 0):.4f}")
    m3.metric("Fraud Precision", f"{fraud_report.get('precision', 0):.3f}")
    m4.metric("Fraud Recall", f"{fraud_report.get('recall', 0):.3f}")

    st.divider()

    curve_left, curve_right = st.columns(2)

    with curve_left:
        st.subheader("ROC Curve")
        fig_roc = go.Figure()
        fig_roc.add_trace(go.Scatter(
            x=curves["fpr"], y=curves["tpr"],
            mode="lines",
            name=f"LR (AUC = {metrics['roc_auc']:.4f})",
            line=dict(color="#3498db", width=2),
            fill="tozeroy",
            fillcolor="rgba(52,152,219,0.1)",
        ))
        fig_roc.add_trace(go.Scatter(
            x=[0, 1], y=[0, 1],
            mode="lines",
            name="Random",
            line=dict(color="gray", width=1, dash="dash"),
        ))
        fig_roc.update_layout(
            xaxis_title="False Positive Rate",
            yaxis_title="True Positive Rate",
            plot_bgcolor="rgba(0,0,0,0)",
            legend=dict(yanchor="bottom", y=0.05, xanchor="right", x=0.95),
            margin=dict(t=20),
        )
        st.plotly_chart(fig_roc, use_container_width=True)

    with curve_right:
        st.subheader("Precision-Recall Curve ★")
        fig_pr = go.Figure()
        fig_pr.add_trace(go.Scatter(
            x=curves["recall"], y=curves["precision"],
            mode="lines",
            name=f"LR (AP = {metrics['pr_auc']:.4f})",
            line=dict(color="#e67e22", width=2),
            fill="tozeroy",
            fillcolor="rgba(230,126,34,0.1)",
        ))
        baseline = stats.get("fraud_rate", 0.0017)
        fig_pr.add_hline(y=baseline, line_dash="dash", line_color="gray",
                         annotation_text=f"Baseline ({baseline*100:.2f}%)")
        fig_pr.update_layout(
            xaxis_title="Recall",
            yaxis_title="Precision",
            plot_bgcolor="rgba(0,0,0,0)",
            legend=dict(yanchor="top", y=0.95, xanchor="right", x=0.95),
            margin=dict(t=20),
        )
        st.plotly_chart(fig_pr, use_container_width=True)

    st.divider()

    cm_col, feat_col = st.columns(2)

    with cm_col:
        st.subheader("Confusion Matrix")
        cm = metrics.get("confusion_matrix", [[0, 0], [0, 0]])
        labels = ["Legitimate (0)", "Fraud (1)"]
        fig_cm = go.Figure(go.Heatmap(
            z=cm,
            x=labels,
            y=labels,
            colorscale=[[0, "#f8f9fa"], [1, "#e74c3c"]],
            text=[[str(v) for v in row] for row in cm],
            texttemplate="%{text}",
            textfont={"size": 20},
            showscale=False,
        ))
        fig_cm.update_layout(
            xaxis_title="Predicted",
            yaxis_title="Actual",
            height=350,
            margin=dict(t=20),
        )
        st.plotly_chart(fig_cm, use_container_width=True)

    with feat_col:
        st.subheader("Top 15 Feature Importances (|coefficient|)")
        if top_features:
            feat_names = [f[0] for f in top_features]
            feat_vals = [f[1] for f in top_features]
            colors = ["#e74c3c" if v > 0 else "#3498db" for v in feat_vals]
            fig_feat = go.Figure(go.Bar(
                x=[abs(v) for v in feat_vals],
                y=feat_names,
                orientation="h",
                marker_color=colors,
                text=[f"{v:+.3f}" for v in feat_vals],
                textposition="outside",
            ))
            fig_feat.update_layout(
                xaxis_title="|Coefficient|",
                plot_bgcolor="rgba(0,0,0,0)",
                yaxis=dict(autorange="reversed"),
                height=350,
                margin=dict(t=20, r=60),
            )
            st.plotly_chart(fig_feat, use_container_width=True)
            st.caption("Red = positive coefficient (→ higher fraud probability), Blue = negative.")

    st.divider()
    st.subheader("Full Classification Report")
    if report:
        report_rows = []
        for label, vals in report.items():
            if isinstance(vals, dict):
                report_rows.append({
                    "Class": label,
                    "Precision": f"{vals.get('precision', 0):.3f}",
                    "Recall": f"{vals.get('recall', 0):.3f}",
                    "F1-Score": f"{vals.get('f1-score', 0):.3f}",
                    "Support": int(vals.get("support", 0)),
                })
        st.dataframe(pd.DataFrame(report_rows), use_container_width=True, hide_index=True)

# ══════════════════════════════════════════════════════════════════════════════
# TAB 4 — Pipeline Details
# ══════════════════════════════════════════════════════════════════════════════
with tab4:
    st.header("⚙️ Pipeline & Architecture")

    st.subheader("MLOps Pipeline Stages")
    st.markdown("""
| Stage | Script | Description |
|---|---|---|
| **Preprocess** | `mlops_pipeline.py --stage preprocess` | Shuffle → stratified split (70/10/20) → `StandardScaler` → save `.npz` + `preprocessor.joblib` |
| **Train** | `mlops_pipeline.py --stage train` | Load `train.npz` + `val.npz` → LogisticRegression → save `model.joblib` → print `val_auc` JSON |
| **Evaluate** | `mlops_pipeline.py --stage evaluate` | Load `test.npz` → ROC-AUC, PR-AUC, classification report → save JSON |
| **Demo** | `train_demo.py` | All-in-one: generate synthetic data → train → pickle bundle for Streamlit |
""")

    st.divider()

    left_col, right_col = st.columns(2)

    with left_col:
        st.subheader("Preprocessing")
        st.code("""
# src/data/preprocess.py
SEED = 42
TEST_SIZE = 0.20   # 20 % held out for test
VAL_SIZE  = 0.10   # 10 % of remaining = val

# 1. Shuffle dataset
df = df.sample(frac=1, random_state=SEED)

# 2. Stratified train/val/test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=TEST_SIZE, stratify=y, random_state=SEED
)
X_train, X_val, y_train, y_val = train_test_split(
    X_train, y_train, test_size=VAL_SIZE/(1-TEST_SIZE),
    stratify=y_train, random_state=SEED
)

# 3. StandardScaler (fit on train only)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_val   = scaler.transform(X_val)
X_test  = scaler.transform(X_test)

# 4. Save to .npz + preprocessor.joblib
        """, language="python")

    with right_col:
        st.subheader("Model Training")
        st.code("""
# src/models/train.py
from sklearn.linear_model import LogisticRegression

# Compute balanced class weights manually
classes, counts = np.unique(y_train, return_counts=True)
total = len(y_train)
class_weight = {
    int(c): total / (len(classes) * cnt)
    for c, cnt in zip(classes, counts)
}

model = LogisticRegression(
    class_weight=class_weight,
    max_iter=1000,
    random_state=42,
    solver="lbfgs",
)
model.fit(X_train, y_train)

# Validation metric
val_auc = roc_auc_score(y_val, model.predict_proba(X_val)[:, 1])
print(json.dumps({"val_auc": val_auc}))

joblib.dump(model, "artifacts/model.joblib")
        """, language="python")

    st.divider()

    st.subheader("Class Imbalance Strategy")
    st.markdown("""
Credit card fraud datasets are severely imbalanced (~0.17 % fraud). This pipeline handles imbalance via:

1. **Balanced class weights** — each fraudulent transaction is up-weighted by
   `n_samples / (n_classes × n_fraud_samples)`, penalising misclassification of the minority class more heavily.

2. **Stratified splits** — all three splits (train/val/test) preserve the original fraud ratio,
   preventing artificially clean or difficult evaluation sets.

3. **PR-AUC as primary metric** — Precision-Recall AUC captures model quality on the minority class
   without being inflated by the large number of true negatives (legitimate transactions).
    """)

    st.divider()

    st.subheader("Key Design Decisions")
    cols = st.columns(3)
    with cols[0]:
        st.info("**Why Logistic Regression?**\n\nInterpretable coefficients, fast inference, no feature interaction assumptions needed when V1-V28 are already decorrelated by PCA.")
    with cols[1]:
        st.warning("**Why StandardScaler?**\n\nAmount and Time have very different scales compared to PCA V-features (which are already ~N(0,1)). Scaling prevents gradient instability.")
    with cols[2]:
        st.error("**Why not accuracy?**\n\nA model predicting 'always legitimate' achieves >99.8% accuracy on Kaggle data. Accuracy is useless here — always use PR-AUC or F1 for fraud.")

    st.divider()

    st.subheader("Project Structure")
    st.code("""
credit-card-fraud-detection/
├── .github/workflows/ci.yml     # CI: matrix 3.11/3.12, lint, codecov
├── configs/
│   └── train_config.yaml        # Pipeline configuration
├── data/
│   ├── raw/                     # Raw input CSVs (git-ignored)
│   └── processed/               # Preprocessed .npz files (git-ignored)
├── artifacts/
│   ├── model.joblib             # Trained model (git-ignored)
│   ├── fraud_demo.pkl           # Streamlit demo bundle ✅
│   └── eval_report.json         # Evaluation report
├── src/
│   ├── data/load.py             # CSV loader
│   ├── data/preprocess.py       # Stratified split + StandardScaler
│   ├── features/build_features.py  # Feature engineering
│   ├── models/train.py          # LogisticRegression training
│   ├── models/evaluate.py       # ROC-AUC / PR-AUC evaluation
│   └── visualization/plots.py   # Matplotlib plotting utilities
├── tests/                       # 5 unit tests (all passing)
├── flask_app.py                 # REST API (/health, /predict)
├── mlops_pipeline.py            # CLI orchestrator
├── train_demo.py                # Standalone demo trainer
├── streamlit_app.py             # This app
├── requirements.txt
├── requirements-ci.txt          # Lean CI dependencies
└── README.md
    """, language="text")

    st.caption("Built with scikit-learn · Streamlit · Plotly · GitHub Actions")
